# Where the homeserver's Client-Server API is located. Typically this
# is where clients would be connecting to in order to send messages.
homeserverUrl: "https://matrix.org"

# An access token for the bot to use. Learn how to get an access token
# at https://t2bot.io/docs/access_tokens
accessToken: "YOUR_TOKEN_HERE"

# Whether or not to autojoin rooms when invited.
autoJoin: false

# Location on disk for where to store various bot information.
dataPath: "storage"

profile:
    displayname: "Zammad Bot"
    avatar: true

# Generate a personal access within Zammad to use it with the bot.
# https://user-docs.zammad.org/en/latest/extras/profile-and-settings.html
zammad:
    url: "https://example.com"
    accessToken: "YOUR_PERSONAL_ZAMMAD_API_TOKEN"
    
# The ID of you matrix room(s) you want to receive Zammad's ticket
# notifications.
rooms:
    - "ID_OF_RECEIVING_MATRIX_ROOM"

sender_tokens:
    - "YOUR_USER_ID": "YOUR_SENDER_TOKEN"
